//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetails
    {
        public int order_details_id { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> qty { get; set; }
        public string ProductName { get; set; }
        public string Imageurl { get; set; }
    
        public virtual Orders customer_Orders { get; set; }
    }
}
