//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularjsDemo.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_Products
    {
        public int product_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string ImageUrl { get; set; }
        public Nullable<int> price { get; set; }
        public string ProductName { get; set; }
    }
}
